### ISSUE TITLE
Faults

### ISSUE THREAD

**Issue by Pricelss** [Raajheer1/IDS#28]
Issue with activating the current landing and departing runways. Not sure if its just a bad build on my mac, but wont update after selection and confirming. 

Document viewer pulls up charts, but not ZDV control documents. Not sure if thats an issue with the server or website?

**Comment by Raajheer1** [comment]
Runways have been fixed, there was an expired SSL Certificate, it should all be functional again.

Documents are 50/50 this issue was brought up to the web team a few months ago and was resolved on Feb. 20th, ZDV-Website issue #64 for reference. I'm not sure if it will ever be fixed, I don't understand the current ZDV Website Structure so I am unable to resolve that issue myself.
